---
language: java
jdk:
  - oraclejdk7
env:
  global:
    - "PATH=/tmp/spring-1.1.1.RELEASE/bin:/tmp/play-2.2.3:$PATH"
before_install:
  - "wget http://downloads.typesafe.com/play/2.2.3/play-2.2.3.zip -qO /tmp/play.zip"
  - "unzip -qd /tmp /tmp/play.zip"
  - "curl https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.1.1.RELEASE/spring-boot-cli-1.1.1.RELEASE-bin.tar.gz -s | tar xzf - -C /tmp"
install: true
script: TERM=dumb ./gradlew
notifications:
  webhooks:
    urls:
      - http://build-monitor.cfapps.io/projects/JTA/webhook
    on_start: true
