language: java
jdk:
- oraclejdk8
env:
  global:
  - PATH=/tmp/spring-1.2.3.RELEASE/bin:/tmp/activator-1.3.2-minimal:$PATH
before_install:
- wget http://downloads.typesafe.com/typesafe-activator/1.3.2/typesafe-activator-1.3.2-minimal.zip
  -qO /tmp/activator.zip
- unzip -qd /tmp /tmp/activator.zip
- curl https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
  -s | tar xzf - -C /tmp
install: true
script: ./gradlew
notifications:
  slack:
    secure: XVkOKVNUiO3efnKH05cmC+JtPxJCzC5zOg1J/BCOhxfvQ5JjvHlXeDrm/HmQ5c7EhRHMIZ1ltrv8Gk+M412o7pMFQCZSNGmTGkFmb86pJ/V8/nMxr8C+/H92ApStnvH+WVmMQ1MIdszm9Js9M+S+DR/OaltXEBzpQ4Qz7AIdyS8=
  webhooks:
    urls:
    - http://build-monitor.cfapps.io/projects/JTA/webhook
    on_start: true
