---
language: java
jdk:
  - oraclejdk7
env:
  global:
    - "PATH=/tmp/spring-1.0.0.RC1/bin:/tmp/play-2.2.1:$PATH"
before_install:
  - "wget http://downloads.typesafe.com/play/2.2.1/play-2.2.1.zip -qO /tmp/play.zip"
  - "unzip -qd /tmp /tmp/play.zip"
  - "curl https://repo.spring.io/milestone/org/springframework/boot/spring-boot-cli/1.0.0.RC1/spring-boot-cli-1.0.0.RC1-bin.tar.gz -s | tar xzf - -C /tmp"
install: true
script: TERM=dumb ./gradlew
notifications:
  webhooks: "http://build-monitor.cfapps.io/projects/JTA/webhook"
